// <auto-generated />
using System;
using MeuAcervo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeuAcervo.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525182423_IdentityAuthPhase")]
    partial class IdentityAuthPhase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeuAcervo.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f7c36fe-6d36-4a94-8d8f-e1d222b07901"),
                            Code = "library.read",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite visualizar o acervo.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7db8c8d0-fc1f-4df4-9699-0e8dc2305a02"),
                            Code = "library.write",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite alterar o acervo.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("59848cc7-5d14-4c74-9d71-1294bd6cbe03"),
                            Code = "wishlist.read",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite visualizar a wishlist.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f01be170-c8c5-4a1d-892a-fcf48cf6ea04"),
                            Code = "wishlist.write",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite alterar a wishlist.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2d22b8a9-1c99-4e1f-b5c7-1f897dbcc405"),
                            Code = "reviews.read",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite visualizar reviews.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22a45dbf-bd9c-425a-a5c6-87b9a5664206"),
                            Code = "reviews.write",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite criar e editar reviews.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8a0fbd47-0cfe-48a0-8d35-a76215ce2807"),
                            Code = "tags.read",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite visualizar tags.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("584214b8-c3f7-4458-b34b-a2c5d3ca1308"),
                            Code = "tags.write",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite alterar tags.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c80d8454-c9b3-45d9-b794-948b25a9a809"),
                            Code = "loans.read",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite visualizar empréstimos.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("91313f53-8bc8-4b44-a1b9-0664c9099e10"),
                            Code = "loans.write",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite alterar empréstimos.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("52fbdb1f-8b2d-49a2-aab4-c494fe2bf011"),
                            Code = "custom-fields.read",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite visualizar campos customizados.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa738999-18d5-40d6-9f88-8810cc09c112"),
                            Code = "custom-fields.write",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite alterar campos customizados.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3034ee58-f9b1-42f7-b7ff-9222ab7f2613"),
                            Code = "profile.read",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite visualizar configurações de perfil.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6eb47857-20f4-4891-993a-f89ec0fc2214"),
                            Code = "profile.write",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite alterar configurações de perfil.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b71be4c3-46d7-45ea-a1c8-06f319d41215"),
                            Code = "admin.roles.manage",
                            CreatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permite gerenciar roles e permissões.",
                            UpdatedAtUtc = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MeuAcervo.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.Role", b =>
                {
                    b.HasOne("MeuAcervo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("MeuAcervo.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeuAcervo.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.User", b =>
                {
                    b.HasOne("MeuAcervo.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("MeuAcervo.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuAcervo.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MeuAcervo.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
